version: '3'
services:
  celery:
      container_name: celery
      image: "celery:0.20"
      ports:
       - "8090:8090"
      networks:
      - backend
      privileged: true

  nginx:
      container_name: nginx
      image: "nginx:0.20"
      #image: "docker.io/hunetailab/nginx:celery"
      ports:
       - "80:80"
       - "81:81"
       - "443:443"
      volumes:
       - /var/log/nginx:/var/log/nginx
      networks:
       - backend
      privileged: true

networks:
  backend:
    driver: bridge