version: '3'
services:

  api:
    container_name: api
    image: "api:0.01"
    ports:
     - "7077:7070"
    volumes:
      - ./api/static/data_collection:/home/gomata/src/api/static/data_collection
#      - /home/ubuntu/src/data_collection:/home/gomata/src/api/static
    networks:
    - backend
    privileged: true
    environment:
            TZ : "Asia/Seoul"

  frontend-dev:
    container_name: frontend-dev
    image: "frontend-dev:0.01"
    build:
      context: ./frontend
      dockerfile: Dockerfile-dev
    ports:
      - "3030:3000"
    networks:
      - backend
    privileged: true
    stdin_open: true
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
           - TZ="Asia/Seoul"
           - CHOKIDAR_USEPOLLING=true
    command: yarn start
            
  nginx:
    container_name: nginx
    image: "nginx:0.01"
    ports:
      - "80:80"
      - "81:81"
      - "443:443"
    volumes:
      - ./nginx/container_log:/var/log/nginx
    networks:
      - backend
    privileged: true
    environment:
            TZ : "Asia/Seoul"
            
networks:
  backend:
    driver: bridge
