version: '3'
services:

  api:
    container_name: api
    image: "api:0.01"
    ports:
     - "8099:8090"
    networks:
    - backend
    privileged: true

  frontend-dev:
    container_name: frontend-dev
    image: "frontend-dev:0.01"
    ports:
      - "3030:3000"
    networks:
      - backend
    privileged: true
    stdin_open: true

  nginx:
    container_name: nginx
    image: "nginx:0.01"
    ports:
      - "80:80"
      - "81:81"
      - "443:443"
    volumes:
      - ./nginx/container_log:/var/log/nginx
    networks:
      - backend
    privileged: true

networks:
  backend:
    driver: bridge